services:
  - type: web
    name: wingo-app
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000